services:
  wordpress:
    image: wordpress:latest
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
    - wordpress_data:/var/www/html
    - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    - ./wp-content:/var/www/html/wp-content
    depends_on:
    - db
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_DATABASE: wpdb
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
    - db_data:/var/lib/mysql
    - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: wpuser
      PMA_PASSWORD: wppass
      UPLOAD_LIMIT: 32M
    depends_on:
    - db
volumes:
  wordpress_data: null
  db_data: null
